apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    app: demo1
  template:
    metadata:
      name: demo
      labels:
        app: demo1
    spec:
      containers:
        - name: nginx
          image: shivendra013/shiva
          ports:
            - containerPort: 80
              name: ngin

